name = "TensegrityEquilibria"
uuid = "dcaeff44-b3e3-40bb-9039-8883ea4974a9"
authors = ["Matthias Himmelmann <matthias.himmelmann@outlook.de>"]
version = "0.1.3"

[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
GLMakie = "0.2"
julia = "1.4"
HomotopyContinuation = "2.5.3"
AbstractPlotting = "0.17.2"
